<a href="https://colab.research.google.com/github/shashwats976-ai/Data-science-/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
data = pd.read_csv("/content/drive/MyDrive/Ass 5 dataset.csv")

## Q1 [Load & Inspect]

In [ ]:
# Display shape
print(f"DataFrame Shape: {data.shape}")

# Display columns
print("DataFrame Columns:")
print(data.columns.tolist())

# Display dtypes
print("DataFrame Data Types:")
print(data.dtypes)

# Display head(5)
print("\nFirst 5 rows:")
display(data.head(5))

# Display tail(3)
print("\nLast 3 rows:")
display(data.tail(3))

DataFrame Shape: (10, 8)
DataFrame Columns:
['StudentID', 'Name', 'Age', 'City', 'Department', 'Score', 'Grade', 'Passed']
DataFrame Data Types:
StudentID     object
Name          object
Age            int64
City          object
Department    object
Score          int64
Grade         object
Passed          bool
dtype: object

First 5 rows:

  StudentID          Name  Age     City Department  Score Grade  Passed
0      S001   Arjun Mehta   21    Delhi        CSE     78     B    True
1      S002  Divya Sharma   22   Mumbai        ECE     91     A    True
2      S003   Karan Patel   20     Pune        CSE     55     C    True
3      S004    Meera Nair   23  Chennai       MECH     42     D    True
4      S005   Sahil Gupta   21    Delhi        ECE     88     A    True

Last 3 rows:

  StudentID           Name  Age     City Department  Score Grade  Passed
7      S008    Pooja Yadav   23  Chennai        CSE     92     A    True
8      S009    Vivek Kumar   21     Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22    Delhi       MECH     58     C    True

## Q2 [describe/info]

In [ ]:
# Run df.info()
print("DataFrame Info:")
data.info()

# Run df.describe()
print("\nDataFrame Description:")
describe_df = data.describe()
display(describe_df)

# Extract mean Score and standard deviation
mean_score = describe_df.loc['mean', 'Score']
std_score = describe_df.loc['std', 'Score']
print(f"\nMean Score: {mean_score:.2f}")
print(f"Standard Deviation of Score: {std_score:.2f}")

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   10 non-null     object
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   City        10 non-null     object
 4   Department  10 non-null     object
 5   Score       10 non-null     int64
 6   Grade       10 non-null     object
 7   Passed      10 non-null     bool
dtypes: bool(1), int64(2), object(5)
memory usage: 702.0+ bytes

DataFrame Description:

             Age      Score
count  10.000000  10.000000
mean   21.500000  67.700000
std     1.080123  20.133168
min    20.000000  35.000000
25%    21.000000  55.750000
50%    21.500000  69.000000
75%    22.000000  85.500000
max    23.000000  92.000000

Mean Score: 67.70
Standard Deviation of Score: 20.13

## Q3 [Column Access]

In [ ]:
# Access the 'Name' column
print("\n'Name' column:")
display(data['Name'].head())

# Access 'Score' and 'Grade' columns together
print("\n'Score' and 'Grade' columns:")
display(data[['Score', 'Grade']].head())

'Name' column:

0     Arjun Mehta
1    Divya Sharma
2     Karan Patel
3      Meera Nair
4     Sahil Gupta
Name: Name, dtype: object

'Score' and 'Grade' columns:

   Score Grade
0     78     B
1     91     A
2     55     C
3     42     D
4     88     A

## Q4 [loc]

In [ ]:
# (a) row at index 0
print("\nRow at index 0 (using loc):")
display(data.loc[0])

# (b) rows 2 to 5
print("\nRows 2 to 5 (using loc):")
display(data.loc[2:5])

# (c) rows 0–4 but only columns Name, Score, Grade
print("\nRows 0-4 and columns 'Name', 'Score', 'Grade' (using loc):")
display(data.loc[0:4, ['Name', 'Score', 'Grade']])

Row at index 0 (using loc):

StudentID            S001
Name          Arjun Mehta
Age                    21
City                Delhi
Department            CSE
Score                  78
Grade                   B
Passed               True
Name: 0, dtype: object

Rows 2 to 5 (using loc):

  StudentID          Name  Age     City Department  Score Grade  Passed
2      S003   Karan Patel   20     Pune        CSE     55     C    True
3      S004    Meera Nair   23  Chennai       MECH     42     D    True
4      S005   Sahil Gupta   21    Delhi        ECE     88     A    True
5      S006  Anjali Singh   22   Jaipur        CSE     35     F   False

Rows 0-4 and columns 'Name', 'Score', 'Grade' (using loc):

           Name  Score Grade
0   Arjun Mehta     78     B
1  Divya Sharma     91     A
2   Karan Patel     55     C
3    Meera Nair     42     D
4   Sahil Gupta     88     A

## Q5 [iloc]

In [ ]:
# (a) first 3 rows
print("\nFirst 3 rows (using iloc):")
display(data.iloc[0:3])

# (b) last 2 rows
print("\nLast 2 rows (using iloc):")
display(data.iloc[-2:])

# (c) rows at positions 1, 3, 5 and columns at positions 0, 2, 4
print("\nRows at positions 1, 3, 5 and columns at positions 0, 2, 4 (using iloc):")
display(data.iloc[[1, 3, 5], [0, 2, 4]])

First 3 rows (using iloc):

  StudentID          Name  Age    City Department  Score Grade  Passed
0      S001   Arjun Mehta   21   Delhi        CSE     78     B    True
1      S002  Divya Sharma   22  Mumbai        ECE     91     A    True
2      S003   Karan Patel   20    Pune        CSE     55     C    True

Last 2 rows (using iloc):

  StudentID           Name  Age   City Department  Score Grade  Passed
8      S009    Vivek Kumar   21   Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22  Delhi       MECH     58     C    True

Rows at positions 1, 3, 5 and columns at positions 0, 2, 4 (using iloc):

  StudentID  Age Department
1      S002   22        ECE
3      S004   23       MECH
5      S006   22        CSE

## Q6 [Boolean Filter] Filter students where Score > 80. How many students scored above 80?

In [ ]:
high_score_students = data[data['Score'] > 80]
print("Students with Score > 80:")
display(high_score_students)
print(f"Number of students who scored above 80: {len(high_score_students)}")

Students with Score > 80:

  StudentID          Name  Age     City Department  Score Grade  Passed
1      S002  Divya Sharma   22   Mumbai        ECE     91     A    True
4      S005   Sahil Gupta   21    Delhi        ECE     88     A    True
7      S008   Pooja Yadav   23  Chennai        CSE     92     A    True

Number of students who scored above 80: 3

## Q7 [Boolean Filter] Filter students from Delhi who are in CSE department. Show Name, Score, and Grade only.

In [ ]:
delhi_cse_students = data[(data['City'] == 'Delhi') & (data['Department'] == 'CSE')]
print("Students from Delhi in CSE department:")
display(delhi_cse_students[['Name', 'Score', 'Grade']])

Students from Delhi in CSE department:

          Name  Score Grade
0  Arjun Mehta     78     B

## Q8 [Boolean Filter] Find all students who Failed (Passed == False). What is their average Score?

In [ ]:
failed_students = data[data['Passed'] == False]
print("Students who Failed:")
display(failed_students)
print(f"Average Score of failed students: {failed_students['Score'].mean():.2f}")

Students who Failed:

  StudentID          Name  Age    City Department  Score Grade  Passed
5      S006  Anjali Singh   22  Jaipur        CSE     35     F   False

Average Score of failed students: 35.00

## Q9 [String Filter] Filter students whose Name contains the string 'a' (case-insensitive) using `.str.contains()`.

In [ ]:
name_contains_a = data[data['Name'].str.contains('a', case=False, na=False)]
print("Students whose Name contains 'a' (case-insensitive):")
display(name_contains_a)

Students whose Name contains 'a' (case-insensitive):

  StudentID           Name  Age     City Department  Score Grade  Passed
0      S001    Arjun Mehta   21    Delhi        CSE     78     B    True
1      S002   Divya Sharma   22   Mumbai        ECE     91     A    True
2      S003    Karan Patel   20     Pune        CSE     55     C    True
3      S004     Meera Nair   23  Chennai       MECH     42     D    True
4      S005    Sahil Gupta   21    Delhi        ECE     88     A    True
5      S006   Anjali Singh   22   Jaipur        CSE     35     F   False
6      S007    Rohan Verma   20   Mumbai       MECH     67     B    True
7      S008    Pooja Yadav   23  Chennai        CSE     92     A    True
8      S009    Vivek Kumar   21     Pune        ECE     71     B    True
9      S010  Nisha Agarwal   22    Delhi       MECH     58     C    True

## Q10 [Add Column] Add a new column 'Score_Category': if Score >= 80 → 'Distinction', Score >= 60 → 'Merit', else 'Pass/Fail'. Use `np.where()` or nested condition.

In [ ]:
import numpy as np

data['Score_Category'] = np.where(data['Score'] >= 80, 'Distinction',
                                  np.where(data['Score'] >= 60, 'Merit', 'Pass/Fail'))
print("DataFrame with 'Score_Category' column added:")
display(data.head())

DataFrame with 'Score_Category' column added:

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,S001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
1,S002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,S003,Karan Patel,20,Pune,CSE,55,C,True,Pass/Fail
3,S004,Meera Nair,23,Chennai,MECH,42,D,True,Pass/Fail
4,S005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction

## BONUS Sort the DataFrame by Score in descending order. Reset the index. Show the top 5 students.

In [ ]:
sorted_data = data.sort_values(by='Score', ascending=False).reset_index(drop=True)
print("Top 5 students by Score (descending) with reset index:")
display(sorted_data.head(5))

Top 5 students by Score (descending) with reset index:

,StudentID,Name,Age,City,Department,Score,Grade,Passed,Score_Category
0,S008,Pooja Yadav,23,Chennai,CSE,92,A,True,Distinction
1,S002,Divya Sharma,22,Mumbai,ECE,91,A,True,Distinction
2,S005,Sahil Gupta,21,Delhi,ECE,88,A,True,Distinction
3,S001,Arjun Mehta,21,Delhi,CSE,78,B,True,Merit
4,S009,Vivek Kumar,21,Pune,ECE,71,B,True,Merit